webtalk_init -webtalk_dir C:/Users/air/Desktop/gitFPGA/FPGAproject/project/2_counter/2_counter.sim/sim_1/behav/xsim/xsim.dir/m_counter_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Nov 29 16:55:42 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d271cf21-4b3b-4ba3-91f9-1c1a9eed014c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3d78e7fe6a0b49caab4afb7a06e17f52" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "16" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 7735H with Radeon Graphics        " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3194 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7512_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2125890342 -regid "" -xml C:/Users/air/Desktop/gitFPGA/FPGAproject/project/2_counter/2_counter.sim/sim_1/behav/xsim/xsim.dir/m_counter_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/air/Desktop/gitFPGA/FPGAproject/project/2_counter/2_counter.sim/sim_1/behav/xsim/xsim.dir/m_counter_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/air/Desktop/gitFPGA/FPGAproject/project/2_counter/2_counter.sim/sim_1/behav/xsim/xsim.dir/m_counter_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
